---
title: "Idées"
---

# Type de données : Mensuelles

Regarder comment on fait pour les dates. \# Site des données :

[Policy uncertainly](http://www.policyuncertainty.com/)

# Variables Y :

Cours du pétrole WTI , Données mensuelles, Période : 1987-2023

## Variables X :

1.  Var : [CPU Climate policy uncertainly](http://www.policyuncertainty.com/climate_uncertainty.html) x

2.  Var : [Economic Policy Uncertainty Index for United States](https://fred.stlouisfed.org/series/USEPUINDXD) x

3.  Var : [Economic Policy Uncertainty Index for China](https://fred.stlouisfed.org/series/CHIEPUINDXM) x

4.  Var : [Equity Market Volatility Tracker: Overall](https://fred.stlouisfed.org/series/EMVOVERALLEMV) x

5.  Var : [Equity Market Volatility Tracker: Energy And Environmental Regulation](https://fred.stlouisfed.org/series/EMVENRGYENVREG) x

6.  Var : [Equity Market Volatility Tracker: Commodity Markets](https://fred.stlouisfed.org/series/EMVCOMMMKT) x

7.  Var: [Equity Market Volatility Tracker: Elections And Political Governance](https://fred.stlouisfed.org/series/EMVELECTGOVRN) x

8.  Var : [Cours spot de l'or](https://www.investing.com/currencies/xau-usd-historical-data) x

9.  Var : [Natural Gas spot price](https://www.eia.gov/naturalgas/data.php) Problème : 1997, x

10. Var : [Euro-Dollars](https://www.investing.com/currencies/eur-usd-historical-data) x

11. Var : [Global price of Iron Ore](https://fred.stlouisfed.org/series/PIORECRUSDM) x

12. Var :[Consumer Price Index for All Urban Consumers: All Items Less Food and Energy in U.S. City Average](https://fred.stlouisfed.org/series/CPILFESL) x

13. Var : [Producer Price Index by Commodity: Nonmetallic Mineral Products: Hydraulic Fracturing Sand and All Other Industrial Sand](https://fred.stlouisfed.org/series/WPU13990121) x

14. Var : [University of Michigan: Consumer Sentiment](https://fred.stlouisfed.org/series/UMCSENT) x

15. Var : [Federal fund effective rate](https://fred.stlouisfed.org/series/fedfunds) x

**Premiere déselection**

-   [Equity Market Volatility Tracker: Monetary Policy](https://fred.stlouisfed.org/series/EMVMONETARYPOL) 0

-   [Equity Market Volatility Tracker: Exchange Rates](https://fred.stlouisfed.org/series/EMVEXRATES) o

-   [Economic Policy Uncertainty Index: Categorical Index: Health care](https://fred.stlouisfed.org/series/EPUHEALTHCARE) o

-   [Economic Policy Uncertainty Index: Categorical Index: Sovereign debt, currency crises](https://fred.stlouisfed.org/series/EPUSOVDEBT) o

-   [Equity Market Volatility: Infectious Disease Tracker](https://fred.stlouisfed.org/series/INFECTDISEMVTRACK) o

-   [Geopolitical risk index](https://www.matteoiacoviello.com/gpr.htm) o

-   alternative : EU Gas Prices [1990-2023](https://uk.investing.com/commodities/natural-gas-historical-data) o

-   [Financial Stress Indicator](http://www.policyuncertainty.com/financial_stress.html) o

-   [World Uncertainty Index for Islamic Republic of Iran](https://fred.stlouisfed.org/series/WUIIRN) 0
